Fix FESK on_sequence_ready callback signature mismatch
The on_sequence_ready callback requires a different signature:
  void (*)(const int8_t *sequence, size_t entries, void *user_data)

But the *_on_ready functions have signature:
  void (*)(void *user_data)

Fixed by:
- fesk_demo_face.c: Removed on_sequence_ready assignment (functionality
  already covered by on_transmission_end)
- fesk_lite_demo_face.c: Changed on_sequence_ready to on_transmission_end
- uptime_face.c: Removed on_sequence_ready and added title display to
  on_transmission_end and on_cancelled callbacks

Fixes compilation error:
- incompatible function pointer types assigning to 'fesk_session_sequence_cb'